import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/utils/Providers";
import React from "react";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Providers>{children}</Providers>
        <Toaster
          toastOptions={{
            position: "top-center",
            style: {
              color: "white",
              backgroundColor: "#151419",
            },
          }}
        />
      </body>
    </html>
  );
}
